# CMD: docker compose -f local-mysql-db.yml up
version: '3.1'

services:
  local-mysql-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
    ports:
      - '3306:3306'
    expose:
      - '3306'
